server:
  port: 8080
  servlet:
    context-path: /SuperUser
  error:
    include-message: always #获取异常详细信息message

spring:
  application:
    name: SuperUserServer
  boot:
    admin:
      client:
        url: http://localhost:8880
        instance:
          service-host-type: ip
          metadata:
            user:
              name: admin
              password: 123456
        username: admin
        password: 123456
  security:
    user:
      name: admin
      password: 123456

# management 是所有actuator的配置
# management.endpoint.端点名.xxxx  对某个端点的具体配置
management:
  endpoints:
    enabled-by-default: true  #默认开启所有监控端点  true
    web:
      exposure:
        include: '*' # 以web方式暴露所有端点

  endpoint:   #对某个端点的具体配置
    health:
      show-details: always
      enabled: true

    info:
      enabled: true

    beans:
      enabled: true

    metrics:
      enabled: true

#设置日志级别，root表示根节点，即整体应用日志级别
logging:
  level:
    root: info
#  file:
#    path: 'logs/server.log'
  #设置日志文件名字，回滚日志相关参数
  file:
    name: 'logs/server.log'
  logback:
    rollingpolicy:
      max-file-size: 1MB
      file-name-pattern: "logs/server.log.%d{yyyy-MM-dd_HH}.%i.log"
      max-history: 720

globalconfig:
  urlForCrossingModel: ""
  urlForMissingModel: ""
  mainPath: ""
  cropImageBin: "${globalconfig.mainPath}/..."
  dataPath: "${globalconfig.mainPath}/..."
  tmpDir: "${globalconfig.mainPath}/..."
  imageDir: "${globalconfig.mainPath}/..."
  cropprocess: 50