server:
  port: 8080
  servlet:
    context-path: /SuperUser
  error:
    include-message: always #获取异常详细信息message

spring:
  application:
    name: SuperUserServer
  boot:
    admin:
      client:
        url: http://localhost:8880/SuperUserAdmin
        instance:
          service-host-type: ip
          metadata:
            user:
              name: admin
              password: 123456
        username: admin
        password: 123456
  security:
    user:
      name: admin
      password: 123456
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

# management 是所有actuator的配置
# management.endpoint.端点名.xxxx  对某个端点的具体配置
management:
  endpoints:
    enabled-by-default: true  #默认开启所有监控端点  true
    web:
      exposure:
        include: '*' # 以web方式暴露所有端点

  endpoint:   #对某个端点的具体配置
    health:
      show-details: always
      enabled: true

    info:
      enabled: true

    beans:
      enabled: true

    metrics:
      enabled: true

#设置日志级别，root表示根节点，即整体应用日志级别
logging:
  level:
    root: info
#  file:
#    path: 'logs/server.log'
  #设置日志文件名字，回滚日志相关参数
  file:
    name: 'logs/server.log'
  logback:
    rollingpolicy:
      max-file-size: 1MB
      file-name-pattern: "logs/server.log.%d{yyyy-MM-dd_HH}.%i.log"
      max-history: 60

globalconfig:
  urlForGetBBImage: "http://114.117.165.134:26000/dynamic/image/cropimage"
  urlForGetBBSwc: "http://114.117.165.134:26000/dynamic/swc/cropswc"
  urlForGetImageList: "http://114.117.165.134:26000/dynamic/image/getimagelist"
  urlForCrossingModel: "http://114.117.165.134:26004/predictions"
  urlForMissingModel: "http://114.117.165.134:26003/predictions"
  urlForBranchingModel: "http://114.117.165.134:26013/predictions"
  mainPath: "/home/BraintellServer"
  cropImageBin: "${globalconfig.mainPath}/vaa3d/cropimage"
  dataPath: "${globalconfig.mainPath}/data"
  tmpDir: "${globalconfig.mainPath}/tmp"
  imageDir: "${globalconfig.mainPath}/image"
  savePathForPredict: "/home/zhy/tmpDirForPredict"
  tipPatchSize: [32,32,32]
  branchingPatchSize: [64,64,64]
  crossingPatchSize: [32,32,32]
  cropprocess: 50
  username: zackzhy
  password: 123456